
project_id = "pvkzzkbwjntazemosbot"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_manual_linking = false

[db]
port = 54322

[functions.sync-odoo-employees]
verify_jwt = false

[functions.sync-odoo-projects]
verify_jwt = false

[functions.bulk-sync-odoo-projects]
verify_jwt = false

[realtime]
enabled = true
port = 54323

[storage]
enabled = true
port = 54324

[studio]
enabled = true
port = 54323
