
project_id = "pvkzzkbwjntazemosbot"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://pvkzzkbwjntazemosbot.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.ai-search-query]
verify_jwt = true

[functions.bulk-create-users]
verify_jwt = true

[functions.bulk-delete-users]
verify_jwt = true

[functions.bulk-update-users]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.export-users]
verify_jwt = true

[functions.list-settings]
verify_jwt = true

[functions.send-profile-email]
verify_jwt = true

[functions.update-user]
verify_jwt = true
